import argparse
import os
import json

def convert_to_markdown(filepath):
    """
    Converts a JSON output from googleNews.py into a nice markdown string.

    Args:
        filename (str): Name of JSON file to read from.
 
    Returns:
        str: Markdown formatted string displaying all headlines, questions, and answers.
    """
    # read json file in
    with open(filepath, "r", encoding="utf-8") as file:
        full_data = json.load(file)

    # separate client name and data
    client = full_data['client']
    data = full_data['data']

    # initialize output string with title and description
    output = f"# Output from {filepath}\n"
    output += f"\nThese are the top stories from Google News, along with the questions and answers generated by {client}.\n"

    # iterate over each headline
    for headline_obj in data:
        # add title with link
        title = headline_obj["headline"]
        outlet = headline_obj["news-outlet"]
        url = headline_obj["url"]
        output += f"\n## [{title} ({outlet})]({url})\n"

        # add questions and answers
        qas = headline_obj["questions"]
        for qa in qas:
            # parse the question dictionary
            question = qa["question"]
            answer = qa["answer"]
            citations = qa["citations"]

            # add to markdown string
            output += f"\n### {question}\n"
            output += f"\n{answer}\n"
            output += f"\nCitations: {", ".join(citations)}\n"
    return output

def main():
    # parse arguments
    parser = argparse.ArgumentParser(description = "Convert a JSON output from googleNews.py into a nice markdown file.")
    parser.add_argument("input", help = "Input JSON file to convert to markdown.")
    args = parser.parse_args()

    # open json file and parse into md
    md = convert_to_markdown(args.input)
    # save to file
    file_out = f"{os.path.splitext(args.input)[0]}.md"
    with open(file_out, 'w') as file:
        file.write(md)

if __name__ == "__main__":
    main()